### ISSUE TITLE
de-Glenat-ify blurb

### ISSUE THREAD

**Issue by ghost** [LinuxGamer/pepper-carrot-novel#1]
I saw in the Matrix chat that you pulled the blurb from the back of the Glenat edition, which is perfectly fine for the most part. However, there are two parts that may confuse English-speakers:
* in the comic text, the forest in which the Chaosahn witches live is named "Squirrel's End", not "Bout-un-Cureuil";
* 'Mélusine' is a reference by analogy to a French comic also featuring a witch.

**Comment by orbitalmartian8** [comment]
Thank you for pointing these out, I did wonder whether these were correct, I did google and web translate them but nothing really came up. Thanks again.
